<?php

namespace Database\Seeders;

use App\Enums\NatureTypeEnum;
use App\Models\DiagnosticHypothesis;
use App\Models\NatureType;
use Illuminate\Database\Seeder;

class NatureTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $natures = [
            [
                'name' => 'Trauma',
                'id' => NatureTypeEnum::TRAUMA->value,
                'hypotheses' => [
                    'QUEDA DE ALTURA',
                    'QUEIMADURA',
                    'SOTERRAMENTO',
                    'TRAUMA CRANIOENCEFÁLICA (TCE)',
                    'TRAUMA DE ABDOME',
                    'TRAUMA DE TÓRAX',
                    'TRAUMA OCULAR',
                    'TRAUMA RAQUIMEDULAR (TRM)',
                    'AGRESSÃO FÍSICA',
                    'ESTUPRO',
                    'ATROPELAMENTO POR AUTOMÓVEL',
                    'ESMAGAMENTO',
                    'ACIDENTE COM BICICLETA',
                    'ACIDENTE COM CARROÇA',
                    'ACIDENTE COM CAMINHÃO',
                    'ABORDAGEM',
                    'ACIDENTE COM ANIMAIS PEÇONHENTOS',
                    'ACIDENTE COM AUTOMÓVEL',
                    'ACIDENTE COM MOTOCICLETA',
                    'ACIDENTE COM MÚLTIPLAS VÍTIMAS',
                    'ACIDENTE COM ÔNIBUS',
                    'ACIDENTE COM TRANSPORTE AQUÁTICO',
                    'ASFIXIA',
                    'ATAQUE DE ABELHAS',
                    'ATROPELAMENTO POR MOTOCICLETA',
                    'CAPOTAMENTO',
                    'CHOQUE ELETRICO',
                    'COLISÃO AUTOMÓVEL X ÔNIBUS',
                    'COLISÃO AUTOMÓVEL X POSTE',
                    'COLISÃO MOTOCICLETA X MOTOCICLETA',
                    'COLISÃO MOTOCICLETA X ÔNIBUS',
                    'COLISÃO MOTOCICLETA X POSTE',
                    'EMPALAMENTO',
                    'ENFORCAMENTO',
                    'ENTORSE',
                    'ESCORIAÇÕES',
                    'ESTRANGULAMENTO',
                    'FERIMENTO POR ARMA BRANCA (FAB)',
                    'FERIMENTO POR PROJÉTIL DE ARMA DE FOGO (FPAF)',
                    'FERIMENTOS MÚLTIPLOS',
                    'FRATURA DE MEMBRO SUPERIOR',
                    'MORDEDURA POR ANIMAIS',
                    'POLITRAUMA',
                    'QUEDA DA PRÓPRIA ALTURA',
                    'TRAUMA DE ARCOS COSTAIS',
                    'TRAUMA DE BACIA/PELVE',
                    'TRAUMA DE COLUNA',
                    'TRAUMA DE FACE',
                    'TRAUMA DE FEMUR',
                    'TRAUMA DE MÃO',
                    'TRAUMA DE MEMBRO INFERIOR',
                    'TRAUMA DE PÉ',
                    'TRAUMA OCULAR',
                    'TRAUMA DE TÓRAX',
                    'TRAUMAS MÚLTIPLOS',
                    'OUTROS',
                ],
            ],
            [
                'name' => 'Clínico',
                'id' => NatureTypeEnum::CLINICAL->value,
                'hypotheses' => [
                    'ABDOME AGUDO',
                    'ABORDAGEM',
                    'AFECÇAO BOLHOSA',
                    'ALZHEIMER',
                    'AMIGDALITE',
                    'ANAFILAXIA',
                    'ANASARCA',
                    'ANEMIA',
                    'CELULITE',
                    'ANEURISMA',
                    'ANGINA',
                    'APENDICITE AGUDA',
                    'APLASIA DE MEDULA',
                    'APOIO',
                    'ARRITMIA CARDÍACA',
                    'ARTRITE ARTROSE',
                    'ASMA',
                    'NEOPLASIA',
                    'ACIDENTE VASCULAR CEREBRAL (AVC)',
                    'BLOQUEIO ATRIO VENTRICULAR TOTAL (BAVT)',
                    'CHOQUE CIRCULATÓRIO',
                    'BEXIGOMA',
                    'BRONCOESPASMOS',
                    'BRONQUIOLITE',
                    'BRONQUITE',
                    'CEFALEIA',
                    'CHOQUE ANAFILÁTICO',
                    'CIRROSE HEPATICA',
                    'COAGULAÇÃO INTRAVASCULAR DISSEMINADA',
                    'COARCTAÇÃO DA AORTA',
                    'COLANGITE',
                    'COLECISTITE AGUDA',
                    'COLEDOCOLITiASE',
                    'COLELITIASE',
                    'COLICA BILIAR',
                    'CÔLICA NEFRÉTICA',
                    'COLICA RENAL',
                    'COMPLICAÇÕES DE PÓS OPERATÓRIO',
                    'CONVULSÃO',
                    'COVID-19',
                    'DENGUE',
                    'DERMATITE',
                    'DERRAME PLEURAL',
                    'DESIDRATAÇAO',
                    'DESNUTRIÇAO',
                    'DIABETES',
                    'DIARREIA',
                    'DISPNEIA',
                    'DISTURBIO METABOLICO',
                    'DISTONIA AGUDA',
                    'DISTURBIO VISUAL',
                    'DIVERTICULITE',
                    'DOENCA DE CHAGAS',
                    'DOENÇA DE HAUNTING',
                    'DOENÇA DE PRÍONS',
                    'DOENÇA HEMORROIDÁRIA',
                    'DOENÇA INFLAMATORIA PELVICA - DIP',
                    'DOR ABDOMINAL',
                    'DOR MMII',
                    'DOR MMSS',
                    'DPOC',
                    'DST',
                    'EAP',
                    'EMBOLIA PULMONAR',
                    'ENCEFALITE',
                    'ENFISEMA PULMONAR',
                    'ENFISEMA SUBCUTANEO',
                    'ENTERORRAGIA',
                    'ENVENENAMENTO',
                    'ENXAQUECA',
                    'EPIGASTRALGIA',
                    'EPILEPSIA EPISTAXE',
                    'ERISIPELA',
                    'ESCARA INFECTADA',
                    'ESCARAS',
                    'ESCLEROSE ESOFAGITE',
                    'ESTENOSE AORTICA',
                    'ESTENOSE DE TRAQUÉIA',
                    'ESTENOSE MITRAL',
                    'ESTOMATITE',
                    'FARINGITE',
                    'FEBRE',
                    'FEBRE CHIKUNGUNYA',
                    'FEBRE DE ORIGEM INDETERMINADA',
                    'FEOCROMOCITOMA',
                    'FIBROMIALGIA',
                    'FIBROSE CÍSTICA',
                    'FIBROSE PULMONAR',
                    'FISTULA BILIAR',
                    'FISTULA DE DIALISE SANGRANTE FISTULA TRAQUEO ESOFAGICA',
                    'FLUTTER ATRIAL',
                    'FRAQUEZA',
                    'GASTRITE',
                    'GECA',
                    'GNDA',
                    'GNPE',
                    'GOTA',
                    'GRIPE',
                    'H1N1',
                    'HANSENÍASE',
                    'HAS',
                    'HDA',
                    'HDB',
                    'HEMANGIOMA',
                    'HEMATÉMESE',
                    'HEMORRAGIA',
                    'HEPATITE',
                    'HERNIA ABDOMINAL',
                    'HERNIA ENCARCERADA',
                    'HÉRNIA ESTRANGULADA',
                    'HIGROMA',
                    'HIPERGLICEMIA',
                    'HIPOGLICEMIA',
                    'HIPOTENSÃO',
                    'HIPOTIROIDISMO',
                    'HIV',
                    'IAM',
                    'ICC',
                    'INFECÇÃO POR HANTAR VÍRUS',
                    'INSUF RENAL',
                    'INSUFICIÊNCIA RESPIRATÓRIA',
                    'INSUFICIÊNCIA CARDÍACA',
                    'INSUFICIÊNCIA RENAL AGUDA',
                    'INTOXICAÇÃO EXÓGENA',
                    'INTUSSUSCEPÇÃO INTESTINAL',
                    'ISQUEMIA MESENTÉRICA',
                    'ITU',
                    'IVAS',
                    'LARINGITE',
                    'LEISHMANIOSE',
                    'LEUCEMIA',
                    'LIBAÇÃO ETÍLICA',
                    'LINFANGITE',
                    'LINFOMA',
                    'LIPOTIMIA',
                    'LOMBALGIA',
                    'MAL ESTAR',
                    'MASTOIDITE',
                    'MEDIALITE ACTÍNICA',
                    'MEGACOLON TÓXICO',
                    'MELANOMA',
                    'MELENA',
                    'MENINGIOMA MIÍASE',
                    'MENINGITE',
                    'MIALGIA',
                    'MIlASE',
                    'MORTE ENCEFÁLICA',
                    'NEOPLASIA',
                    'NEOPLASIA DE BEXIGA',
                    'NEOPLASIA DE COLUNA',
                    'NEOPLASIA DE GASTRO INTESTINAL',
                    'NEOPLASIA DE LARINGE',
                    'NEOPLASIA DE MAMA',
                    'NEOPLASIA DE PÂNCREAS',
                    'NEOPLASIA DE PULMAO',
                    'NEOPLASIA DE TRÁQUEA',
                    'NEOPLASIA HEPATICA',
                    'NEOPLASIA OSSEA',
                    'NEURALGIA DO TRIGÊMIO',
                    'NEUROTOXOPLASMOSE',
                    'NEUTROPENIA FEBRIL',
                    'OBESIDADE',
                    'ÓBITO CONFIRMADO',
                    'OCLUSÃO ARTERIAL AGUDA',
                    'OSTEOMIELITE',
                    'OTALGIA',
                    'OTORRAGIA',
                    'PANCREATITE',
                    'PARAPLEGIA',
                    'PARKINSON',
                    'PCR',
                    'PERITONITE',
                    'PIELONEFRITE',
                    'PNEUMOCISTOSE',
                    'PNEUMONIA',
                    'PNEUMONIA ASPIRATIVA',
                    'PNEUMOTORÁX',
                    'POLICITEMIA',
                    'POS-ICTAL',
                    'PRECORDIALGIA',
                    'PRIAPISMO',
                    'PROLAPSO DE COLOSTOMIA',
                    'PROLAPSO RETAL',
                    'PSORIASE',
                    'PURPURA TROMBOCITOPÊNICA TROMBÓTICA',
                    'QUEDA ESTADO GERAL RABDOMIOLISE',
                    'RAIVA',
                    'REAÇÃO ALÉRGICA',
                    'REAÇÃO LEUCEMOIDE',
                    'RESTRIÇÃO AO LEITO/NTERNAÇÃO SOCIAL',
                    'RETORNO REUMATISMO',
                    'RINITE ALERGICA',
                    'SARAMPO SEPSE',
                    'SEPSE DE ORIGEM NÃO DETERMINADA',
                    'SIDA SIFILIS SINCOPE',
                    'SINDROME COLESTÁTICA',
                    'SINDROME COMPORTAMENTAL SINDROME DE ABSTINENCIA SINDROME DE CAUDA EQUINA',
                    'SINDROME DE FOURNIER',
                    'SINDROME DE GUILLAIN-BARRE SINDROME DE LEMIERRE',
                    'SINDROME DE PARALISIA MOTORA',
                    'SINDROME DE PIERRE ROBIN',
                    'SINDROME DE STEVENS-JOHNSON',
                    'SINDROME DE WOLFF PARKINSON WHITE',
                    'SINDROME HELLP',
                    'SINDROME MEDULAR AGUDA',
                    'SINDROME NEFRÍTICA',
                    'SINDROME NEFRÓTICA',
                    'SINUSITE',
                    'SRAG',
                    'SUSPEITA DE ÓBITO',
                    'TALASSEMIA TAQUICARDIA',
                    'TÉTANO',
                    'TETRAPLEGIA',
                    'TONTURA',
                    'TORÇÃO TESTICULAR',
                    'TOSSE',
                    'TRANSTORNO OLHO TRANSTORNO OUVIDO',
                    'TROCA DE SONDA',
                    'TROMBOSE',
                    'TROMBOSE MESENTARIA',
                    'TUBERCULOSE',
                    'TUMOR DE WILMS',
                    'ULCERA GASTRICA',
                    'URGÊNCIA DIALÍTICA',
                    'UROLITIASE',
                    'UROSEPSE',
                    'URTICARIA VARICELA VARIZES',
                    'VIAS AÉREAS OBSTRUIDAS VOLVO VOMITOS',
                    'SÍNCOPE',
                    'OUTROS',
                ],
            ],
            [
                'name' => 'Gineco Obstétrico',
                'id' => NatureTypeEnum::GYNECO_OBSTETRIC->value,
                'hypotheses' => [
                    'ABORDAGEM',
                    'ABORTAMENTO',
                    'ABORTO CONCLUÍDO',
                    'ABORTO EM CURSO',
                    'AMNIORREXE PREMATURA',
                    'APOIO',
                    'ATONIA UTERINA',
                    'COLICA MENSTRUAL',
                    'COVID-19',
                    'DESCOLAMENTO PREMATURO DE PLACENTA',
                    'DOENÇA HIPERTENSIVA ESPECÍFICA DA GRAVIDEZ (DHEG)',
                    'ECLAMPSIA',
                    'EMBOLIA AMNIÓTICA',
                    'GESTAÇAO ECTÓPICA ROTA',
                    'DORES ABDOMINAIS EM GESTANTE',
                    'METRORRAGIA',
                    'ÓBITO CONFIRMADO',
                    'PARTO',
                    'PÓS DATISMO',
                    'PRÉ-ECLÂMPSIA',
                    'SIFILIS CONGÊNITA',
                    'TRABALHO DE PARTO',
                    'SUSPEITA DE ABORTAMENTO',
                    'SANTRAMENTO TRANSVAGINAL NA GRAVIDEZ',
                    'DIABETES GESTACIONAL COMPLICADA',
                    'SOFRIMENTO FETAL',
                    'OUTROS',
                ],
            ],
            [
                'name' => 'Pediátrico',
                'id' => NatureTypeEnum::PEDIATRIC->value,
                'hypotheses' => [
                    'ANAFILAXIA',
                    'ARRITIMIA CARDÍACA',
                    'ABDOME AGUDO',
                    'ABORDAGEM',
                    'AMIGDALITE',
                    'INFARTO AGUDO DO MIOCÁRDIO (IAM)',
                    'ACIDENTE VASCULAR CEREBRAL (AVC)',
                    'CETOACIDOSE DIABÉTICA',
                    'CELULITE',
                    'ANEMIA',
                    'ARTROSE',
                    'ANEURISMA',
                    'ANGINA',
                    'APENDICITE',
                    'APOIO',
                    'ARTRITE',
                    'ASFIXIA',
                    'ASMA',
                    'ATEROSCLEROSE',
                    'ATRESIA ESOFÁGICA',
                    'COLICA BILIAR',
                    'COLICA RENAL',
                    'CONVULSAO',
                    'BRONCOESPASMOS',
                    'BRONQUIOLITE',
                    'DESNUTRIÇAO',
                    'COQUELUCHE',
                    'NEOPLASIA',
                    'CEFALEIA',
                    'DIARREIA',
                    'CIRROSE HEPÁTICA',
                    'COLECISTITE',
                    'COVID-19',
                    'DENGUE',
                    'DERMATITE',
                    'DERRAME PLEURAL',
                    'DESIDRATAÇAO',
                    'DIABETES',
                    'DISTÚRBIO METABOLICO',
                    'DIST VISUAL DISTONIA AGUDA DOENÇA DE CHAGAS DOR ABDOMINAL',
                    'DOR EM MEMBRO SUPERIOR',
                    'DOR EM MEMBRO INFERIOR',
                    'EMBOLIA PULMONAR',
                    'ENCEFALITE',
                    'ENFORCAMENTO',
                    'ENTORSE',
                    'ENVENENAMENTO',
                    'ENXAQUECA',
                    'EPIGASTRALGIA',
                    'EPILEPSIA',
                    'EPISTAXE',
                    'ERISIPELA',
                    'ERRO INATO DO METABOLISMO',
                    'ESCLEROSE ESCORIAÇÕES ESMAGAMENTO',
                    'ESOFAGITE',
                    'ESTOMATITE',
                    'FARINGITE AGUDA',
                    'FEBRE',
                    'FRAQUEZA',
                    'HERNIA',
                    'GASTRITE',
                    'GASTROENTEROCOLITE AGUDA (GECA)',
                    'GOTA',
                    'GRIPE',
                    'GRIPE H1N1',
                    'HANSENIASE',
                    'HIPERTENSÃO ARTERIAL AGUDA (HAS)',
                    'HEMORRAGIA DIGESTIVA ALTA (HDA)',
                    'HEMORRAGIA DIGESTIVA BAIXA (HDB)',
                    'HEMATÊMESE',
                    'HEMORRAGIA',
                    'HEMORROIDA',
                    'HEPATITE',
                    'HERNIA ENCARCERADA',
                    'HERNIA ESTRANGULADA',
                    'HIGROMA',
                    'HIPERGLICEMIA',
                    'HIPERPLASIA ADRENAL CONGÊNITA',
                    'HIPOGLICEMIA',
                    'HIPOTENSÃO',
                    'HIPOTIREOIDISMO',
                    'HIV',
                    'INSUFICIÊNCIA CARDÍACA (IC)',
                    'INFECÇÃO DE VIAS AÉREAS SUPERIORES (IVAS)',
                    'INSUFICIÊNCIA RENAL',
                    'INSUFICIÊNCIA RESPIRATÓRIA',
                    'INTOXICAÇAO EXÓGENA',
                    'INFECÇÃO DO TRATO URINÁRIO (ITU)',
                    'LARINGITE AGUDA',
                    'LEUCEMIA',
                    'LIPOTIMIA',
                    'LOMBALGIA',
                    'MEGACOLON TÓXICO',
                    'MENINGITE',
                    'MIALGIA',
                    'MORDIDA POR ANIMAIS',
                    'PIELONEFRITE',
                    'OBITO CONFIRMADO',
                    'ONFALOCELE',
                    'OTORRAGIA',
                    'OBSTRUÇÃO DE VIAS AÉREAS (OVACE)',
                    'PANCREATITE',
                    'PARALISIA CEREBRAL',
                    'PARAPLEGIA',
                    'PARADA CARDIORRESPIRATÓRIA (PCR)',
                    'PERITONITE',
                    'PNEUMONIA',
                    'PNEUMOTORAX',
                    'PRECORDIALGIA',
                    'PSORIASE',
                    'PÚRPURA',
                    'QUEDA ESTADO GERAL',
                    'REUMATISMO',
                    'RINITE ALERGICA',
                    'SIFILIS',
                    'SíNCOPE',
                    'SíNDROME COLESTATICA',
                    'SíNDROME DE DOWN',
                    'SINDROME DE WOLFF PARKINSON WHITE',
                    'SINUSITE',
                    'SUSPEITA OBITO',
                    'TAQUICARDIA',
                    'TETANO',
                    'TETRALOGIA DE FALLOT',
                    'TETRAPLEGIA',
                    'TONTURA',
                    'TOSSE',
                    'TRANSPOSIÇÃO DE GRANDES VASOS',
                    'TRANSTORNO OLHO',
                    'TRANSTORNO OUVIDO',
                    'TROMBOSE',
                    'TUBERCULOSE',
                    'ULCERA PEPTICA',
                    'URTICARIA',
                    'VARICELA',
                    'VARIZES',
                    'VITILIGO',
                    'VOMITOS',
                    'DISPNEIA',
                    'OUTROS',
                ],
            ],
            [
                'name' => 'Psiquiátrico',
                'id' => NatureTypeEnum::PSYCHIATRIC->value,
                'hypotheses' => [
                    'ABSTINÊNCIA',
                    'AGITAÇÃO PSICOMOTORA',
                    'AGRESSIVIDADE',
                    'APOIO',
                    'AUTOAGRESSÃO',
                    'CRISE DE ANSIEDADE',
                    'DISTURBIO COMPORTAMENTAL',
                    'DISTÚRBIO NEUROVEGETATIVO (DNV)',
                    'DROGADITO',
                    'ESQUIZOFRENIA',
                    'ETILISMO',
                    'AGITAÇÃO EM DECORRÊNCIA DE USO DE DROGAS',
                    'OBITO CONFIRMADO',
                    'SURTO PSICÓTICO',
                    'TENTATIVA DE SUICÍDIO',
                    'TRANSTORNO DEPRESSIVO',
                    'OUTROS',
                ],
            ],
            [
                'name' => 'Neonatal',
                'id' => NatureTypeEnum::NEONATAL->value,
                'hypotheses' => [
                    'ABORDAGEM',
                    'SÍNDROME DO DESCONFORTO RESPIRATÓRIO DO RECEM-NASCIDO',
                    'APOIO',
                    'ATRESIA ESOFÁGICA',
                    'BRONCOASPIRAÇÃO',
                    'BRONQUIOLITE',
                    'CARDIOPATIA CONGÊNITA',
                    'COVID-19',
                    'DOENÇA CONGÊNITA NEONATAL',
                    'ERRO INATO DO METABOLISMO',
                    'DISPLASIA BRONCOPULMONAR',
                    'ICTERICIA NEONATAL',
                    'MEGACOLON CONGÊNITO',
                    'OBITO CONFIRMADO',
                    'ONFALOCELE',
                    'PNEUMONIA',
                    'PREMATURIDADE',
                    'RECEM NASCIDO',
                    'SINDROME DE ASPIRAÇÃO MECONIAL',
                    'TETRALOGIA DE FALLOT',
                    'TRANSPOSIÇÃO DE GRANDES VASOS',
                    'SANGRAMENTO INTRAVENTRICULAR CEREBRAL',
                ],
            ],
            [
                'name' => 'Evento',
                'id' => NatureTypeEnum::EVENT->value,
                'hypotheses' => [
                    'APOIO',
                    'OUTRO',
                ],
            ],
        ];

        foreach ($natures as $nature) {
            $hypothesisIds = [];
            foreach ($nature['hypotheses'] as $hypothesis) {
                $createdHypothesis = DiagnosticHypothesis::firstOrCreate([
                    'name' => $hypothesis,
                ]);

                $hypothesisIds[] = $createdHypothesis->id;
            }

            NatureType::firstOrCreate([
                'id' => $nature['id'],
                'name' => $nature['name'],
            ])->diagnosticHypotheses()->sync($hypothesisIds);
        }
    }
}
