<?php

namespace App\Enums;

enum UnitTypeEnum: int
{
    case HEALTH_POST = 1;

    case HEALTH_CENTER_OR_BASIC_UNIT = 2;

    case POLYCLINIC = 4;

    case GENERAL_HOSPITAL = 5;

    case SPECIALIZED_HOSPITAL = 7;

    case MIXED_UNIT = 15;

    case GENERAL_EMERGENCY_ROOM = 20;

    case SPECIALIZED_EMERGENCY_ROOM = 21;

    case ISOLATED_OFFICE = 22;

    case MOBILE_RIVER_UNIT = 32;

    case CLINIC_OR_SPECIALTY_CENTER = 36;

    case DIAGNOSTIC_AND_THERAPEUTIC_SUPPORT_UNIT_SADT_ISOLATED = 39;

    case LAND_MOBILE_UNIT = 40;

    case PHARMACY = 43;

    case HEALTH_SUPERVISION_UNIT = 50;

    case COOPERATIVE_OR_HEALTH_WORKER_ASSIGNMENT_COMPANY = 60;

    case NORMAL_BIRTH_CENTER_ISOLATED = 61;

    case HOSPITAL_DAY_ISOLATED = 62;

    case HEALTH_SERVICES_REGULATION_CENTER = 64;

    case LACEN_CENTRAL_PUBLIC_HEALTH_LABORATORY = 67;

    case HEALTH_MANAGEMENT_CENTER = 68;

    case HEMOTHERAPY_AND_OR_HEMATOLOGY_CARE_CENTER = 69;

    case PSYCHOSOCIAL_CARE_CENTER = 70;

    case FAMILY_HEALTH_SUPPORT_CENTER = 71;

    case INDIGENOUS_HEALTH_CARE_UNIT = 72;

    case PROMPT_SERVICE = 73;

    case ACADEMIC_HEALTH_POLE = 74;

    case TELEHEALTH = 75;

    case EMERGENCY_MEDICAL_REGULATION_CENTER = 76;

    case HOME_CARE_SERVICE_ISOLATED = 77;

    case RESIDENTIAL_CARE_UNIT = 78;

    case ORTHOPEDIC_WORKSHOP = 79;

    case PUBLIC_HEALTH_LABORATORY = 80;

    case ACCESS_REGULATION_CENTER = 81;

    case STATE_ORGAN_NOTIFICATION_PROCUREMENT_AND_DISTRIBUTION_CENTER = 82;

    case HEALTH_PROMOTION_AND_DISEASE_PREVENTION_CENTER = 83;

    case SUPPLY_CENTER = 84;

    case IMMUNIZATION_CENTER = 85;

    public function message(): string
    {
        return match ($this) {
            self::HEALTH_POST => 'POSTO DE SAÚDE',
            self::HEALTH_CENTER_OR_BASIC_UNIT => 'CENTRO DE SAÚDE/UNIDADE BÁSICA',
            self::POLYCLINIC => 'POLICLÍNICA',
            self::GENERAL_HOSPITAL => 'HOSPITAL GERAL',
            self::SPECIALIZED_HOSPITAL => 'HOSPITAL ESPECIALIZADO',
            self::MIXED_UNIT => 'UNIDADE MISTA',
            self::GENERAL_EMERGENCY_ROOM => 'PRONTO SOCORRO GERAL',
            self::SPECIALIZED_EMERGENCY_ROOM => 'PRONTO SOCORRO ESPECIALIZADO',
            self::ISOLATED_OFFICE => 'CONSULTÓRIO ISOLADO',
            self::MOBILE_RIVER_UNIT => 'UNIDADE MÓVEL FLUVIAL',
            self::CLINIC_OR_SPECIALTY_CENTER => 'CLÍNICA/CENTRO DE ESPECIALIDADE',
            self::DIAGNOSTIC_AND_THERAPEUTIC_SUPPORT_UNIT_SADT_ISOLATED => 'UNIDADE DE APOIO DIAGNOSE E TERAPIA (SADT ISOLADO)',
            self::LAND_MOBILE_UNIT => 'UNIDADE MÓVEL TERRESTRE',
            self::PHARMACY => 'FARMÁCIA',
            self::HEALTH_SUPERVISION_UNIT => 'UNIDADE DE VIGILÂNCIA EM SAÚDE',
            self::COOPERATIVE_OR_HEALTH_WORKER_ASSIGNMENT_COMPANY => 'COOPERATIVA OU EMPRESA DE CESSÃO DE TRABALHADORES NA SAÚDE',
            self::NORMAL_BIRTH_CENTER_ISOLATED => 'CENTRO DE PARTO NORMAL - ISOLADO',
            self::HOSPITAL_DAY_ISOLATED => 'HOSPITAL/DIA - ISOLADO',
            self::HEALTH_SERVICES_REGULATION_CENTER => 'CENTRAL DE REGULAÇÃO DE SERVIÇOS DE SAÚDE',
            self::LACEN_CENTRAL_PUBLIC_HEALTH_LABORATORY => 'LABORATÓRIO CENTRAL DE SAÚDE PUBLICA LACEN',
            self::HEALTH_MANAGEMENT_CENTER => 'CENTRAL DE GESTÃO EM SAÚDE',
            self::HEMOTHERAPY_AND_OR_HEMATOLOGY_CARE_CENTER => 'CENTRO DE ATENÇÃO HEMOTERÁPICA E OU HEMATOLÓGICA',
            self::PSYCHOSOCIAL_CARE_CENTER => 'CENTRO DE ATENÇÃO PSICOSSOCIAL',
            self::FAMILY_HEALTH_SUPPORT_CENTER => 'CENTRO DE APOIO À SAÚDE DA FAMÍLIA',
            self::INDIGENOUS_HEALTH_CARE_UNIT => 'UNIDADE DE ATENÇÃO À SAÚDE INDÍGENA',
            self::PROMPT_SERVICE => 'PRONTO ATENDIMENTO',
            self::ACADEMIC_HEALTH_POLE => 'POLO ACADEMIA DA SAÚDE',
            self::TELEHEALTH => 'TELESSAÚDE',
            self::HOME_CARE_SERVICE_ISOLATED => 'SERVIÇO DE ATENÇÃO DOMICILIAR ISOLADO (HOME CARE)',
            self::RESIDENTIAL_CARE_UNIT => 'UNIDADE DE ATENÇÃO EM REGIME RESIDENCIAL',
            self::ORTHOPEDIC_WORKSHOP => 'OFICINA ORTOPÉDICA',
            self::PUBLIC_HEALTH_LABORATORY => 'LABORATÓRIO DE SAÚDE PUBLICA',
            self::ACCESS_REGULATION_CENTER => 'CENTRAL DE REGULAÇÃO DO ACESSO',
            self::EMERGENCY_MEDICAL_REGULATION_CENTER => 'CENTRAL DE REGULAÇÃO MÉDICA DAS URGÊNCIAS',
            self::STATE_ORGAN_NOTIFICATION_PROCUREMENT_AND_DISTRIBUTION_CENTER => 'CENTRAL DE NOTIFICAÇÃO, CAPTAÇÃO E DISTRIB DE ÓRGÃOS ESTADUAL',
            self::HEALTH_PROMOTION_AND_DISEASE_PREVENTION_CENTER => 'POLO DE PREVENÇÃO DE DOENÇAS E AGRAVOS E PROMOÇÃO DA SAÚDE',
            self::SUPPLY_CENTER => 'CENTRAL DE ABASTECIMENTO',
            self::IMMUNIZATION_CENTER => 'CENTRO DE IMUNIZAÇÃO',
        };
    }
}
