name: Build and deploy container app - prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: 'ubuntu-latest'
    environment:
      name: main
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: | 
          ghcr.io/gruposynerx/samu-ce-server-prod:latest
        platforms: linux/amd64
        # Removido build-args sensíveis!
        # Caso queira passar algum build-arg público, declare aqui

    - name: Trigger Dokploy Deployment
      run: |
        curl -X 'POST' \
          'https://${{ secrets.DOKPLOY_DOMAIN }}/api/application.deploy' \
          -H 'accept: application/json' \
          -H 'Content-Type: application/json' \
          -H 'x-api-key: ${{ secrets.DOKPLOY_KEY }}' \
          -d '{
            "applicationId": "${{ secrets.DOKPLOY_APPLICATION_ID }}"
          }'
